---
title: "API work"
author: "Haoheng Tang"
date: "3/2/2021"
output: rmarkdown::github_document
---
## 1. Setup

### 1.1 Load packages

```{r load packages, include=TRUE, echo=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(geojsonsf)
library(QuantPsyc)
library(RSocrata)
library(viridis)
library(caret)
library(spatstat)
library(spdep)
library(FNN)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)
library(tidycensus)

library(mapview)
library(httr)
library(dplyr)
library(readxl)
library(stringr)
```

### 1.2 Load fire data

```{r load fire data, include=TRUE, echo=FALSE, message=FALSE}
library(readxl)
fire <- read_excel("./data/fire.xlsx")
library(stringr)

fire1 = fire %>%
  filter(addr_type ==1)
fire1$address <- paste(ifelse(is.na(fire1$number)==FALSE,fire1$number,''),
                       "%20",
                       ifelse(is.na(fire1$st_prefix)==FALSE,fire1$st_prefix,''),
                       ifelse(is.na(fire1$st_prefix)==FALSE,"%20",''),
                       ifelse(is.na(fire1$street)==FALSE,fire1$street,''),
                       "%20",
                       ifelse(is.na(fire1$st_type)==FALSE,fire1$st_type,''), sep = "")
fire2 = fire %>%
  filter(addr_type ==2)
fire2$address <- paste(ifelse(is.na(fire2$xst_prefix)==FALSE,fire2$xst_prefix,''),
                       ifelse(fire2$xst_prefix!='',"%20",''),
                       ifelse(is.na(fire2$xstreet)==FALSE,fire2$xstreet,''),
                       "%20",
                       ifelse(is.na(fire2$xst_type)==FALSE,fire2$xst_type,''),
                       "%20",
                       "&",
                       "%20",
                       ifelse(is.na(fire2$st_prefix)==FALSE,fire2$st_prefix,''), 
                       ifelse(fire2$st_prefix!='',"%20",''),
                       ifelse(is.na(fire2$street)==FALSE,fire2$street,''), 
                       "%20",
                       ifelse(is.na(fire2$st_type)==FALSE,fire2$st_type,''),
                       sep = "")  
```


## 2. Request opa_account_num & parcel_id & census_tract&block

```{r opa_account_num & parcel_id, include=TRUE, echo=TRUE, message=FALSE}
fireData <- rbind(fire1, fire2) %>%
  dplyr::select(address)

fireData$MUSA_ID <- paste0("MUSA_",1:nrow(fireData))

for (i in 1:50) {
  address  <- fireData$address[[i]]
  base_url <- "http://api.phila.gov/ais/v1/"
  endpoint <- "search/"
  key      <- "?gatekeeperKey=dc953bbc4ade9d00eabf5409f6d73d3e"
  url <- paste(base_url, endpoint, address, key, sep="")
  response <- httr::GET(url)
  tidy_res <- httr::content(response, simplifyVector=TRUE)
  if (length(tidy_res) != 4){
    if(length(tidy_res$features$properties$opa_account_num)==2)
      opa_num <-  tidy_res$features$properties$opa_account_num[2]
    else
      opa_num <-  tidy_res$features$properties$opa_account_num[1]
    if(is.null(opa_num)){
      opa_num <- "OPA IS NULL"
    } else if(nchar(opa_num)==0) {
      opa_num <- "OPA IS ZERO LENGTH"
    }
    cat("Address",i,"OPA#:",opa_num,"\n")
    fireData[i,"opa_account_num"] <- opa_num
  }else{
    cat("Address",i,"NO ADDRESS FOUND!","\n")
    fireData[i,"opa_account_num"] <- "NONE FOUND"
  }
  
  if (length(tidy_res) != 4){
    if(length(tidy_res$features$properties$dor_parcel_id)==2)
      parcel_id <-  tidy_res$features$properties$dor_parcel_id[2]
    else
      parcel_id <-  tidy_res$features$properties$dor_parcel_id[1]
    if(is.null(parcel_id)){
      parcel_id <- "PARCEL_ID IS NULL"
    } else if(nchar(parcel_id)==0) {
      parcel_id <- "0LENGTH"
    }
    cat("Address",i,"parcel_id#:",parcel_id,"\n")
    fireData[i,"parcel_id"] <- parcel_id
  }else{
    cat("Address",i,"NO ADDRESS FOUND!","\n")
    fireData[i,"parcel_id"] <- "NONE FOUND"
  }
  
  if(length(tidy_res) != 4){
    if(length(tidy_res$features$properties$census_tract_2010)==2){
      census_tract <-  tidy_res$features$properties$census_tract_2010[2]}
    else{
      census_tract <- tidy_res$features$properties$census_tract_2010
    }
    if(length(tidy_res$features$properties$census_block_2010)==2){
      census_block <-  tidy_res$features$properties$census_block_2010[2]}
    else{
      census_block <- tidy_res$features$properties$census_block_2010
    }
    fireData[i,"census_tract"] <- as.character(census_tract)
    cat("Address",i,"census_tract#:",census_tract,"\n")
    fireData[i,"census_block"] <- as.character(census_block)
    cat("Address",i,"census_block#:",census_block,"\n")
  }else{
    cat("Address",i,"NO ADDRESS FOUND!","\n")
    fireData[i,"census_tract"] <- "NONE FOUND"
    fireData[i,"census_block"] <- "NONE FOUND"
  }
}

fireData <- fireData %>%
  mutate(parcel_id = ifelse(str_count(parcel_id)==10,parcel_id,substr(parcel_id,1,10)))
```

## 3. Request potential feature data

### 3.1 Parcel geometry

```{r parcel, include=TRUE, echo=TRUE, message=FALSE}
DOR_Parcel <- fireData[1:50,]

for (i in 1:50) {
  if(DOR_Parcel$parcel_id[[i]] != "0LENGTH" && DOR_Parcel$parcel_id[[i]] != "NONE FOUND" &&DOR_Parcel$parcel_id[[i]] != "PARCEL_ID IS NULL"){
      base <- "https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/DOR_Parcel/FeatureServer/0/query?outFields=*&where=BASEREG%3D%27"
      BASEREG <- DOR_Parcel$parcel_id[[i]]
      end <- "%27&returnCentroid=true&f=pjson"
      dor_url <- paste(base, BASEREG, end, sep="")
      get_dor <- httr::GET(dor_url)
      dor_data <- httr::content(get_dor, simplifyVector=TRUE, as = "parsed", type = "application/json")
      DOR_Parcel[i,"Parcel_OBJECTID"] <- dor_data$features$attributes$OBJECTID
      DOR_Parcel[i,"PARCEL"] <- dor_data$features$attributes$PARCEL
      DOR_Parcel[i,"Shape__Area"] <- dor_data$features$attributes$Shape__Area
      DOR_Parcel[i,"Shape__Length"] <- dor_data$features$attributes$Shape__Length
      DOR_Parcel[i,"ADDR_SOURCE"] <- dor_data$features$attributes$ADDR_SOURCE
      DOR_Parcel[i,"x"] <- dor_data$features$centroid$x
      DOR_Parcel[i,"y"] <- dor_data$features$centroid$y
  }

}

DOR_Parcel.sf <- DOR_Parcel %>%
  drop_na(x)%>%
  st_as_sf(coords = c("x","y"), crs = 3857)

```

### 3.2 L&I violation

```{r L&I violation, include=TRUE, echo=TRUE, message=FALSE}
violation <- fireData[1:50,]

for (i in 1:50) {
  base_url <- "https://phl.carto.com/api/v2/"
  endpoint <- "sql"
  query    <- c("?q=SELECT%20*%20FROM%20violations%20WHERE%20opa_account_num%20=%20")
  opa_num  <- paste0("%27",fireData$opa_account_num[[i]],"%27")
  url <- paste(base_url, endpoint, query, opa_num, sep="")
  response <- httr::GET(url)
  tidy_res <- httr::content(response, simplifyVector=TRUE)
  
  if (response$status_code != 400){
    if(length(tidy_res$rows$violationcode)==1){
    vio_code <-  tidy_res$rows$violationcode
    vio_title <- tidy_res$rows$violationcodetitle
  
    violation$vio_code[[i]] <- vio_code
    violation$vio_title[[i]] <- vio_title
    
    cat("Address",i,vio_code, vio_title, "\n")}
    else{
    violation$vio_code[[i]] <- "NO CODE VIOLATION"
    violation$vio_title[[i]] <- "NO CODE VIOLATION"
    cat("Address",i,"NO CODE VIOLATION\n")
    }
  }
  else{
    violation$vio_code[[i]] <- "NO RESPONSE"
    violation$vio_title[[i]] <- "NO RESPONSE"
    cat("Address",i,"NO RESPONSE\n")
  }
}
```

### 3.3 Properties

```{r Properties, include=TRUE, echo=TRUE, message=FALSE}
#"https://phl.carto.com/api/v2/sql?q=SELECT * FROM opa_properties_public"

properties <- fireData[1:50,]

for (i in 1:50) {
  base_url <- "https://phl.carto.com/api/v2/"
  endpoint <- "sql"
  query    <- c("?q=SELECT%20*%20FROM%20opa_properties_public%20WHERE%20parcel_number%20=%20")
  opa_num  <- paste0("%27",properties$opa_account_num[[i]],"%27")
  prop_url <- paste(base_url, endpoint, query, opa_num, sep="")
  response_prop <- httr::GET(prop_url)
  tidy_res_prop <- httr::content(response_prop, simplifyVector=TRUE)
  
  if (response_prop$status_code != 400){
    total_area <-  tidy_res_prop$rows$total_area
    total_livable_area <- tidy_res_prop$rows$total_livable_area
    zoning <- tidy_res_prop$rows$zoning
    category_code <- tidy_res_prop$rows$category_code
    category <- case_when(category_code == 1 ~ "Residential",
                          category_code == 2 ~ "Hotels and Apartments",
                          category_code == 3 ~ "Store with Dwelling",
                          category_code == 4 ~ "Commercial",
                          category_code == 5 ~ "Industrial",
                          category_code == 6 ~ "Vacant Land")
    interior_condition <- tidy_res_prop$rows$interior_condition
    interior <- case_when(interior_condition == 0 ~ "Not Applicable",
                          interior_condition == 2 ~ "New/Rehabbed",
                          interior_condition == 3 ~ "Above Average",
                          interior_condition == 4 ~ "Average",
                          interior_condition == 5 ~ "Below Average",
                          interior_condition == 6 ~ "Vacant",
                          interior_condition == 7 ~ "Sealed/Structurally Compromised")
  
    properties$total_area[[i]] <- total_area
    properties$total_livable_area[[i]] <- total_livable_area
    properties$zoning[[i]] <- zoning
    properties$category[[i]] <- category
    properties$interior[[i]] <- interior
    
    cat("\nAddress",i,"total_area", total_area)
    cat("   total_livable_area", total_livable_area)
    cat("   zoning", zoning)
    cat("   category", category)
    cat("   interior", interior)
    }
  else{
    properties$total_area[[i]] <- "NO RESPONSE"
    properties$total_livable_area[[i]] <- "NO RESPONSE"
    properties$zoning[[i]] <- "NO RESPONSE"
    properties$category[[i]] <- "NO RESPONSE"
    properties$interior[[i]] <- "NO RESPONSE"
    cat("\nAddress",i,"NO RESPONSE")
  }
}
```

### 3.4 311 request

```{r 311 request, include=TRUE, echo=TRUE, message=FALSE}
ref311 = "https://phl.carto.com/api/v2/sql?q=SELECT * FROM public_cases_fc WHERE requested_datetime >= '2021-03-01' AND requested_datetime < '2021-03-15' AND lat < "
#"AND lat > "
#"AND lon < "
#"AND lon > "

base311 = ("https://phl.carto.com/api/v2/sql?q=SELECT%20*%20FROM%20public_cases_fc%20WHERE%20requested_datetime%20%3e%3d%20%272021-03-01%27%20AND%20requested_datetime%20%3c%20%272021-03-15%27%20AND%20lat%20%3C%20")
where1 = "AND%20lat%20%3E%20"
where2 = "AND%20lon%20%3C%20"
where3 = "AND%20lon%20%3E%20"

lat =39.97164
lng = -75.16505

url311 <- paste(base311, lat+0.002, where1, lat-0.002, where2, lng+0.002, where3, lng-0.002, sep="")


response311 <- httr::GET(url311)
tidy_res311 <- httr::content(response311, simplifyVector=TRUE)

request311 <- tidy_res311$rows %>%
  data.frame() %>%
  dplyr::select(service_request_id, status, service_name, service_code, requested_datetime, updated_datetime, address, lat, lon)%>%
  drop_na(lat)
```


## 4. Make functions

```{r make functions, include=TRUE, echo=TRUE, message=FALSE}
request <- function(address){
  
  # Request opa -------------------------------------------------
  base_url <- "http://api.phila.gov/ais/v1/"
  endpoint <- "search/"
  key      <- "?gatekeeperKey=dc953bbc4ade9d00eabf5409f6d73d3e"
  url <- paste(base_url, endpoint, address, key, sep="")
  response <- httr::GET(url)
  tidy_res <- httr::content(response, simplifyVector=TRUE)
  if (length(tidy_res) != 4){
    if(length(tidy_res$features$properties$opa_account_num)==2)
      opa_num <-  tidy_res$features$properties$opa_account_num[2]
    else
      opa_num <-  tidy_res$features$properties$opa_account_num[1]
    if(is.null(opa_num)){
      opa_num <- "OPA IS NULL"
    } else if(nchar(opa_num)==0) {
      opa_num <- "OPA IS ZERO LENGTH"
    }
    cat("Address",i,"OPA#:",opa_num,"\n")
    #fireData[i,"opa_account_num"] <- opa_num
  }else{
    cat("Address",i,"NO ADDRESS FOUND!","\n")
    #fireData[i,"opa_account_num"] <- "NONE FOUND"
  }
  
  if (length(tidy_res) != 4){
    if(length(tidy_res$features$properties$dor_parcel_id)==2)
      parcel_id <-  tidy_res$features$properties$dor_parcel_id[2]
    else
      parcel_id <-  tidy_res$features$properties$dor_parcel_id[1]
    if(is.null(parcel_id)){
      parcel_id <- "PARCEL_ID IS NULL"
    } else if(nchar(parcel_id)==0) {
      parcel_id <- "0LENGTH"
    }
    cat("Address",i,"parcel_id#:",parcel_id,"\n")
    #fireData[i,"parcel_id"] <- parcel_id
  }else{
    cat("Address",i,"NO ADDRESS FOUND!","\n")
    #fireData[i,"parcel_id"] <- "NONE FOUND"
  }
}

```

